### ISSUE TITLE
Export ValidatePayload

### ISSUE THREAD

**Issue by cobbinma** [workos-inc/workos-go#128]
hey guys 👋

apologies if i've got this wrong but should `validatePayload` be exported in the `webhooks` package?

```go
func validatePayload(workosHeader string, bodyString string, secret string, defaultTolerance time.Duration) (string, error)
```

as it stands i can only access the errors.

**Comment by mthadley** [comment]
Thanks again for noticing, and fixing this!

In [`1.6.0`](https://github.com/workos-inc/workos-go/releases/tag/v1.6.0), you should now be able to construct a `webhooks.Client`, and then call `ValidatePayload`.

If you run into any issues, feel free to open another issue, contact us, etc
