### ISSUE TITLE
Missing Fields on Directory Sync User

### ISSUE THREAD

**Issue by cobbinma** [workos-inc/workos-go#136]
Noticed `directory_id` and `idp_id` are missing on the [user](https://github.com/workos-inc/workos-go/blob/4914678ac452096ecb6d725f6f125bd2fa004dd1/pkg/directorysync/client.go#L78) object in directory sync https://workos.com/docs/reference/directory-sync/user.

Also the state constant `inactive` is not there.

Can these be added? 🙏

**Comment by logangingerich** [comment]
Thanks for reporting! I just published a released adding these fields here: https://github.com/workos-inc/workos-go/releases/tag/v1.6.1
