### ISSUE TITLE
Export Public Error Functions 

### ISSUE THREAD

**Issue by cobbinma** [workos-inc/workos-go#83]
Can you export public error helper functions so i can easily tell what the cause of an error is?

Example of this below; a helper to tell whether an error is a bad request:
```go
func IsErrorBadRequest(err error) bool {
	httpError, ok := err.(workos.HTTPError)
	if !ok {
		return false
	}

	return httpError.Code == http.StatusBadRequest
}
```

**Comment by ndreas** [comment]
I'm also interested in this, and it would be really nice if we can check the error using the [`errors` package](https://golang.org/pkg/errors/).
